const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const projects = [
  // ===== DATABASES & DATA STORAGE (5 projects) =====
  {
    name: 'PostgreSQL',
    type: 'open-source',
    category: 'Databases & Data Storage',
    description: 'Advanced open-source relational database with ACID compliance, JSON support, and powerful extensions',
    url: 'https://www.postgresql.org',
    githubUrl: 'https://github.com/postgres/postgres',
    logo: '🐘',
    tags: 'database,sql,relational,acid',
    yearCreated: 1996,
    selfHostable: true,
    license: 'PostgreSQL License',
    techStack: 'C,SQL',
    alternativeTo: 'MySQL,Oracle,SQL Server'
  },
  {
    name: 'Redis',
    type: 'open-source',
    category: 'Databases & Data Storage',
    description: 'In-memory data structure store used as database, cache, message broker, and streaming engine',
    url: 'https://redis.io',
    githubUrl: 'https://github.com/redis/redis',
    logo: '🔴',
    tags: 'cache,database,in-memory,nosql',
    yearCreated: 2009,
    selfHostable: true,
    license: 'BSD-3-Clause',
    techStack: 'C',
    alternativeTo: 'Memcached,Valkey,KeyDB'
  },
  {
    name: 'MongoDB',
    type: 'hybrid',
    category: 'Databases & Data Storage',
    description: 'Document-oriented NoSQL database with flexible schema and horizontal scalability',
    url: 'https://www.mongodb.com',
    githubUrl: 'https://github.com/mongodb/mongo',
    logo: '🍃',
    tags: 'database,nosql,document,json',
    yearCreated: 2009,
    selfHostable: true,
    license: 'SSPL',
    techStack: 'C++,JavaScript',
    alternativeTo: 'CouchDB,DynamoDB,Firestore'
  },
  {
    name: 'Supabase',
    type: 'hybrid',
    category: 'Databases & Data Storage',
    description: 'Open-source Firebase alternative with PostgreSQL database, authentication, storage, and real-time subscriptions',
    url: 'https://supabase.com',
    githubUrl: 'https://github.com/supabase/supabase',
    logo: '⚡',
    tags: 'database,backend,postgresql,realtime',
    yearCreated: 2020,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'TypeScript,PostgreSQL,Elixir',
    alternativeTo: 'Firebase,Appwrite,PocketBase'
  },
  {
    name: 'ClickHouse',
    type: 'open-source',
    category: 'Databases & Data Storage',
    description: 'Fast open-source column-oriented database for real-time analytics and OLAP workloads',
    url: 'https://clickhouse.com',
    githubUrl: 'https://github.com/ClickHouse/ClickHouse',
    logo: '⚡',
    tags: 'database,analytics,olap,columnar',
    yearCreated: 2016,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'C++,SQL',
    alternativeTo: 'Snowflake,BigQuery,Druid'
  },

  // ===== WEB FRAMEWORKS & LIBRARIES (5 projects) =====
  {
    name: 'React',
    type: 'open-source',
    category: 'Web Frameworks & Libraries',
    description: 'JavaScript library for building user interfaces with component-based architecture',
    url: 'https://react.dev',
    githubUrl: 'https://github.com/facebook/react',
    logo: '⚛️',
    tags: 'frontend,javascript,ui,library',
    yearCreated: 2013,
    selfHostable: false,
    license: 'MIT',
    techStack: 'JavaScript,TypeScript',
    alternativeTo: 'Vue,Angular,Svelte'
  },
  {
    name: 'Next.js',
    type: 'open-source',
    category: 'Web Frameworks & Libraries',
    description: 'React framework with server-side rendering, static generation, and API routes',
    url: 'https://nextjs.org',
    githubUrl: 'https://github.com/vercel/next.js',
    logo: '▲',
    tags: 'frontend,react,ssr,framework',
    yearCreated: 2016,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,React,Node.js',
    alternativeTo: 'Remix,Gatsby,Nuxt.js'
  },
  {
    name: 'Svelte',
    type: 'open-source',
    category: 'Web Frameworks & Libraries',
    description: 'Compiler-based framework that shifts work to compile time for faster runtime performance',
    url: 'https://svelte.dev',
    githubUrl: 'https://github.com/sveltejs/svelte',
    logo: '🔥',
    tags: 'frontend,javascript,compiler,framework',
    yearCreated: 2016,
    selfHostable: false,
    license: 'MIT',
    techStack: 'TypeScript,JavaScript',
    alternativeTo: 'React,Vue,Solid'
  },
  {
    name: 'Tailwind CSS',
    type: 'open-source',
    category: 'Web Frameworks & Libraries',
    description: 'Utility-first CSS framework for rapidly building custom user interfaces',
    url: 'https://tailwindcss.com',
    githubUrl: 'https://github.com/tailwindlabs/tailwindcss',
    logo: '🎨',
    tags: 'css,styling,utility,frontend',
    yearCreated: 2017,
    selfHostable: false,
    license: 'MIT',
    techStack: 'JavaScript,PostCSS',
    alternativeTo: 'Bootstrap,Material-UI,Chakra UI'
  },
  {
    name: 'Astro',
    type: 'open-source',
    category: 'Web Frameworks & Libraries',
    description: 'Modern static site builder with partial hydration and multi-framework support',
    url: 'https://astro.build',
    githubUrl: 'https://github.com/withastro/astro',
    logo: '🚀',
    tags: 'frontend,static-site,framework,performance',
    yearCreated: 2021,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,Vite',
    alternativeTo: 'Next.js,Gatsby,Eleventy'
  },

  // ===== BACKEND & API FRAMEWORKS (5 projects) =====
  {
    name: 'Express',
    type: 'open-source',
    category: 'Backend & API Frameworks',
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    url: 'https://expressjs.com',
    githubUrl: 'https://github.com/expressjs/express',
    logo: '🚂',
    tags: 'backend,nodejs,api,framework',
    yearCreated: 2010,
    selfHostable: true,
    license: 'MIT',
    techStack: 'JavaScript,Node.js',
    alternativeTo: 'Fastify,Koa,Hapi'
  },
  {
    name: 'FastAPI',
    type: 'open-source',
    category: 'Backend & API Frameworks',
    description: 'Modern, fast Python web framework for building APIs with automatic OpenAPI documentation',
    url: 'https://fastapi.tiangolo.com',
    githubUrl: 'https://github.com/tiangolo/fastapi',
    logo: '⚡',
    tags: 'backend,python,api,async',
    yearCreated: 2018,
    selfHostable: true,
    license: 'MIT',
    techStack: 'Python,Pydantic,Starlette',
    alternativeTo: 'Flask,Django,Tornado'
  },
  {
    name: 'NestJS',
    type: 'open-source',
    category: 'Backend & API Frameworks',
    description: 'Progressive Node.js framework for building efficient, scalable server-side applications',
    url: 'https://nestjs.com',
    githubUrl: 'https://github.com/nestjs/nest',
    logo: '🐱',
    tags: 'backend,nodejs,typescript,framework',
    yearCreated: 2017,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,Node.js,Express',
    alternativeTo: 'Express,Fastify,Adonis'
  },
  {
    name: 'tRPC',
    type: 'open-source',
    category: 'Backend & API Frameworks',
    description: 'End-to-end typesafe APIs with TypeScript, no code generation required',
    url: 'https://trpc.io',
    githubUrl: 'https://github.com/trpc/trpc',
    logo: '🔷',
    tags: 'api,typescript,rpc,type-safety',
    yearCreated: 2020,
    selfHostable: false,
    license: 'MIT',
    techStack: 'TypeScript',
    alternativeTo: 'GraphQL,REST,gRPC'
  },
  {
    name: 'Hono',
    type: 'open-source',
    category: 'Backend & API Frameworks',
    description: 'Ultrafast web framework for edge computing with multi-runtime support',
    url: 'https://hono.dev',
    githubUrl: 'https://github.com/honojs/hono',
    logo: '🔥',
    tags: 'backend,edge,framework,cloudflare',
    yearCreated: 2021,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript',
    alternativeTo: 'Express,Fastify,Elysia'
  },

  // ===== DEVOPS & INFRASTRUCTURE (5 projects) =====
  {
    name: 'Docker',
    type: 'open-source',
    category: 'DevOps & Infrastructure',
    description: 'Platform for developing, shipping, and running applications in containers',
    url: 'https://www.docker.com',
    githubUrl: 'https://github.com/docker/docker-ce',
    logo: '🐳',
    tags: 'containers,devops,deployment,infrastructure',
    yearCreated: 2013,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Go',
    alternativeTo: 'Podman,LXC,containerd'
  },
  {
    name: 'Kubernetes',
    type: 'open-source',
    category: 'DevOps & Infrastructure',
    description: 'Container orchestration platform for automating deployment, scaling, and management',
    url: 'https://kubernetes.io',
    githubUrl: 'https://github.com/kubernetes/kubernetes',
    logo: '☸️',
    tags: 'orchestration,containers,devops,cloud',
    yearCreated: 2014,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Go',
    alternativeTo: 'Docker Swarm,Nomad,ECS'
  },
  {
    name: 'Terraform',
    type: 'open-source',
    category: 'DevOps & Infrastructure',
    description: 'Infrastructure as code tool for building, changing, and versioning infrastructure',
    url: 'https://www.terraform.io',
    githubUrl: 'https://github.com/hashicorp/terraform',
    logo: '🏗️',
    tags: 'iac,devops,infrastructure,automation',
    yearCreated: 2014,
    selfHostable: true,
    license: 'MPL-2.0',
    techStack: 'Go,HCL',
    alternativeTo: 'Pulumi,CloudFormation,Ansible'
  },
  {
    name: 'Nginx',
    type: 'open-source',
    category: 'DevOps & Infrastructure',
    description: 'High-performance web server, reverse proxy, and load balancer',
    url: 'https://nginx.org',
    githubUrl: 'https://github.com/nginx/nginx',
    logo: '🌐',
    tags: 'web-server,proxy,load-balancer,infrastructure',
    yearCreated: 2004,
    selfHostable: true,
    license: 'BSD-2-Clause',
    techStack: 'C',
    alternativeTo: 'Apache,Caddy,Traefik'
  },
  {
    name: 'Prometheus',
    type: 'open-source',
    category: 'DevOps & Infrastructure',
    description: 'Monitoring system and time series database with powerful query language',
    url: 'https://prometheus.io',
    githubUrl: 'https://github.com/prometheus/prometheus',
    logo: '🔥',
    tags: 'monitoring,metrics,observability,timeseries',
    yearCreated: 2012,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Go',
    alternativeTo: 'Grafana Cloud,Datadog,New Relic'
  },

  // ===== AI & MACHINE LEARNING (5 projects) =====
  {
    name: 'PyTorch',
    type: 'open-source',
    category: 'AI & Machine Learning',
    description: 'Deep learning framework with dynamic computation graphs and GPU acceleration',
    url: 'https://pytorch.org',
    githubUrl: 'https://github.com/pytorch/pytorch',
    logo: '🔥',
    tags: 'ai,ml,deep-learning,python',
    yearCreated: 2016,
    selfHostable: false,
    license: 'BSD-3-Clause',
    techStack: 'Python,C++,CUDA',
    alternativeTo: 'TensorFlow,JAX,MXNet'
  },
  {
    name: 'Ollama',
    type: 'open-source',
    category: 'AI & Machine Learning',
    description: 'Run large language models locally with simple API and model management',
    url: 'https://ollama.ai',
    githubUrl: 'https://github.com/ollama/ollama',
    logo: '🦙',
    tags: 'ai,llm,local,inference',
    yearCreated: 2023,
    selfHostable: true,
    license: 'MIT',
    techStack: 'Go,C++',
    alternativeTo: 'LM Studio,GPT4All,llama.cpp'
  },
  {
    name: 'LangChain',
    type: 'open-source',
    category: 'AI & Machine Learning',
    description: 'Framework for developing applications powered by language models with chains and agents',
    url: 'https://www.langchain.com',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    logo: '🦜',
    tags: 'ai,llm,framework,agents',
    yearCreated: 2022,
    selfHostable: false,
    license: 'MIT',
    techStack: 'Python,TypeScript',
    alternativeTo: 'LlamaIndex,Haystack,Semantic Kernel'
  },
  {
    name: 'Hugging Face Transformers',
    type: 'open-source',
    category: 'AI & Machine Learning',
    description: 'State-of-the-art machine learning library for NLP with pre-trained models',
    url: 'https://huggingface.co/transformers',
    githubUrl: 'https://github.com/huggingface/transformers',
    logo: '🤗',
    tags: 'ai,nlp,transformers,models',
    yearCreated: 2018,
    selfHostable: false,
    license: 'Apache-2.0',
    techStack: 'Python,PyTorch,TensorFlow',
    alternativeTo: 'spaCy,AllenNLP,Flair'
  },
  {
    name: 'Stable Diffusion',
    type: 'open-source',
    category: 'AI & Machine Learning',
    description: 'Text-to-image diffusion model for generating high-quality images from text prompts',
    url: 'https://stability.ai',
    githubUrl: 'https://github.com/Stability-AI/stablediffusion',
    logo: '🎨',
    tags: 'ai,image-generation,diffusion,generative',
    yearCreated: 2022,
    selfHostable: true,
    license: 'CreativeML Open RAIL-M',
    techStack: 'Python,PyTorch',
    alternativeTo: 'DALL-E,Midjourney,Imagen'
  },

  // ===== COLLABORATION & PRODUCTIVITY (5 projects) =====
  {
    name: 'Notion',
    type: 'saas',
    category: 'Collaboration & Productivity',
    description: 'All-in-one workspace for notes, docs, wikis, and project management',
    url: 'https://www.notion.so',
    githubUrl: null,
    logo: '📝',
    tags: 'productivity,notes,collaboration,workspace',
    yearCreated: 2016,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'TypeScript,React,Node.js',
    alternativeTo: 'Obsidian,Coda,Confluence'
  },
  {
    name: 'Obsidian',
    type: 'hybrid',
    category: 'Collaboration & Productivity',
    description: 'Powerful knowledge base that works on local Markdown files with graph view',
    url: 'https://obsidian.md',
    githubUrl: null,
    logo: '💎',
    tags: 'notes,markdown,knowledge-base,local',
    yearCreated: 2020,
    selfHostable: true,
    license: 'Proprietary',
    techStack: 'TypeScript,Electron',
    alternativeTo: 'Notion,Roam Research,Logseq'
  },
  {
    name: 'Mattermost',
    type: 'open-source',
    category: 'Collaboration & Productivity',
    description: 'Open-source team collaboration platform with messaging, file sharing, and integrations',
    url: 'https://mattermost.com',
    githubUrl: 'https://github.com/mattermost/mattermost',
    logo: '💬',
    tags: 'chat,collaboration,team,messaging',
    yearCreated: 2015,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Go,React,PostgreSQL',
    alternativeTo: 'Slack,Discord,Microsoft Teams'
  },
  {
    name: 'Linear',
    type: 'saas',
    category: 'Collaboration & Productivity',
    description: 'Issue tracking tool designed for high-performance software teams',
    url: 'https://linear.app',
    githubUrl: null,
    logo: '📊',
    tags: 'project-management,issues,agile,productivity',
    yearCreated: 2019,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'TypeScript,React,GraphQL',
    alternativeTo: 'Jira,Asana,ClickUp'
  },
  {
    name: 'Excalidraw',
    type: 'open-source',
    category: 'Collaboration & Productivity',
    description: 'Virtual whiteboard for sketching hand-drawn like diagrams with collaboration',
    url: 'https://excalidraw.com',
    githubUrl: 'https://github.com/excalidraw/excalidraw',
    logo: '✏️',
    tags: 'whiteboard,diagrams,collaboration,drawing',
    yearCreated: 2020,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,React',
    alternativeTo: 'Miro,FigJam,tldraw'
  },

  // ===== DEVELOPER TOOLS (5 projects) =====
  {
    name: 'VS Code',
    type: 'open-source',
    category: 'Developer Tools',
    description: 'Lightweight but powerful source code editor with rich extension ecosystem',
    url: 'https://code.visualstudio.com',
    githubUrl: 'https://github.com/microsoft/vscode',
    logo: '💻',
    tags: 'editor,ide,development,tools',
    yearCreated: 2015,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,Electron',
    alternativeTo: 'Sublime Text,Atom,IntelliJ IDEA'
  },
  {
    name: 'Git',
    type: 'open-source',
    category: 'Developer Tools',
    description: 'Distributed version control system for tracking changes in source code',
    url: 'https://git-scm.com',
    githubUrl: 'https://github.com/git/git',
    logo: '🌿',
    tags: 'version-control,vcs,development,collaboration',
    yearCreated: 2005,
    selfHostable: true,
    license: 'GPL-2.0',
    techStack: 'C,Shell',
    alternativeTo: 'Mercurial,SVN,Perforce'
  },
  {
    name: 'Postman',
    type: 'hybrid',
    category: 'Developer Tools',
    description: 'API platform for building, testing, and documenting APIs',
    url: 'https://www.postman.com',
    githubUrl: null,
    logo: '📮',
    tags: 'api,testing,development,tools',
    yearCreated: 2012,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'JavaScript,Electron',
    alternativeTo: 'Insomnia,Thunder Client,Bruno'
  },
  {
    name: 'Prettier',
    type: 'open-source',
    category: 'Developer Tools',
    description: 'Opinionated code formatter supporting multiple languages with consistent style',
    url: 'https://prettier.io',
    githubUrl: 'https://github.com/prettier/prettier',
    logo: '✨',
    tags: 'formatter,code-quality,javascript,tools',
    yearCreated: 2017,
    selfHostable: false,
    license: 'MIT',
    techStack: 'JavaScript',
    alternativeTo: 'ESLint,StandardJS,dprint'
  },
  {
    name: 'Vite',
    type: 'open-source',
    category: 'Developer Tools',
    description: 'Next-generation frontend build tool with instant server start and fast HMR',
    url: 'https://vitejs.dev',
    githubUrl: 'https://github.com/vitejs/vite',
    logo: '⚡',
    tags: 'build-tool,bundler,frontend,development',
    yearCreated: 2020,
    selfHostable: false,
    license: 'MIT',
    techStack: 'TypeScript,Rollup,esbuild',
    alternativeTo: 'Webpack,Parcel,Turbopack'
  },

  // ===== SECURITY & AUTHENTICATION (5 projects) =====
  {
    name: 'Keycloak',
    type: 'open-source',
    category: 'Security & Authentication',
    description: 'Open-source identity and access management with SSO and OAuth2/OIDC support',
    url: 'https://www.keycloak.org',
    githubUrl: 'https://github.com/keycloak/keycloak',
    logo: '🔐',
    tags: 'auth,sso,oauth,identity',
    yearCreated: 2014,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Java,Quarkus',
    alternativeTo: 'Auth0,Okta,Azure AD'
  },
  {
    name: 'Bitwarden',
    type: 'open-source',
    category: 'Security & Authentication',
    description: 'Open-source password manager with end-to-end encryption and cross-platform sync',
    url: 'https://bitwarden.com',
    githubUrl: 'https://github.com/bitwarden',
    logo: '🔑',
    tags: 'password-manager,security,encryption,privacy',
    yearCreated: 2016,
    selfHostable: true,
    license: 'GPL-3.0',
    techStack: 'C#,TypeScript,Angular',
    alternativeTo: '1Password,LastPass,Dashlane'
  },
  {
    name: 'Vault',
    type: 'open-source',
    category: 'Security & Authentication',
    description: 'Tool for secrets management, encryption as a service, and privileged access',
    url: 'https://www.vaultproject.io',
    githubUrl: 'https://github.com/hashicorp/vault',
    logo: '🔒',
    tags: 'secrets,security,encryption,devops',
    yearCreated: 2015,
    selfHostable: true,
    license: 'MPL-2.0',
    techStack: 'Go',
    alternativeTo: 'AWS Secrets Manager,Azure Key Vault,Doppler'
  },
  {
    name: 'Authelia',
    type: 'open-source',
    category: 'Security & Authentication',
    description: 'Authentication and authorization server providing 2FA and SSO via web portal',
    url: 'https://www.authelia.com',
    githubUrl: 'https://github.com/authelia/authelia',
    logo: '🛡️',
    tags: 'auth,2fa,sso,security',
    yearCreated: 2016,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Go,React',
    alternativeTo: 'Authentik,Keycloak,Ory'
  },
  {
    name: 'OWASP ZAP',
    type: 'open-source',
    category: 'Security & Authentication',
    description: 'Web application security scanner for finding vulnerabilities in web apps',
    url: 'https://www.zaproxy.org',
    githubUrl: 'https://github.com/zaproxy/zaproxy',
    logo: '🕷️',
    tags: 'security,testing,vulnerability,scanner',
    yearCreated: 2010,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Java',
    alternativeTo: 'Burp Suite,Acunetix,Nessus'
  },

  // ===== CONTENT MANAGEMENT (5 projects) =====
  {
    name: 'WordPress',
    type: 'open-source',
    category: 'Content Management',
    description: 'Popular content management system powering over 40% of the web',
    url: 'https://wordpress.org',
    githubUrl: 'https://github.com/WordPress/WordPress',
    logo: '📰',
    tags: 'cms,blog,website,php',
    yearCreated: 2003,
    selfHostable: true,
    license: 'GPL-2.0',
    techStack: 'PHP,MySQL,JavaScript',
    alternativeTo: 'Drupal,Joomla,Ghost'
  },
  {
    name: 'Strapi',
    type: 'open-source',
    category: 'Content Management',
    description: 'Headless CMS with customizable API, admin panel, and plugin system',
    url: 'https://strapi.io',
    githubUrl: 'https://github.com/strapi/strapi',
    logo: '🚀',
    tags: 'cms,headless,api,nodejs',
    yearCreated: 2015,
    selfHostable: true,
    license: 'MIT',
    techStack: 'JavaScript,Node.js,React',
    alternativeTo: 'Contentful,Sanity,Directus'
  },
  {
    name: 'Ghost',
    type: 'open-source',
    category: 'Content Management',
    description: 'Professional publishing platform with built-in membership and subscription features',
    url: 'https://ghost.org',
    githubUrl: 'https://github.com/TryGhost/Ghost',
    logo: '👻',
    tags: 'cms,blog,publishing,newsletter',
    yearCreated: 2013,
    selfHostable: true,
    license: 'MIT',
    techStack: 'JavaScript,Node.js,Ember',
    alternativeTo: 'WordPress,Medium,Substack'
  },
  {
    name: 'Payload CMS',
    type: 'open-source',
    category: 'Content Management',
    description: 'TypeScript headless CMS with auto-generated APIs and admin UI',
    url: 'https://payloadcms.com',
    githubUrl: 'https://github.com/payloadcms/payload',
    logo: '📦',
    tags: 'cms,headless,typescript,api',
    yearCreated: 2020,
    selfHostable: true,
    license: 'MIT',
    techStack: 'TypeScript,React,MongoDB',
    alternativeTo: 'Strapi,KeystoneJS,Directus'
  },
  {
    name: 'Sanity',
    type: 'hybrid',
    category: 'Content Management',
    description: 'Composable content cloud with real-time collaboration and structured content',
    url: 'https://www.sanity.io',
    githubUrl: 'https://github.com/sanity-io/sanity',
    logo: '✨',
    tags: 'cms,headless,realtime,structured-content',
    yearCreated: 2017,
    selfHostable: false,
    license: 'MIT',
    techStack: 'TypeScript,React',
    alternativeTo: 'Contentful,Strapi,Prismic'
  },

  // ===== COMMUNICATION & MESSAGING (5 projects) =====
  {
    name: 'Slack',
    type: 'saas',
    category: 'Communication & Messaging',
    description: 'Business communication platform with channels, DMs, and extensive integrations',
    url: 'https://slack.com',
    githubUrl: null,
    logo: '💬',
    tags: 'chat,collaboration,team,messaging',
    yearCreated: 2013,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'JavaScript,Electron,React',
    alternativeTo: 'Discord,Microsoft Teams,Mattermost'
  },
  {
    name: 'Discord',
    type: 'saas',
    category: 'Communication & Messaging',
    description: 'Voice, video, and text communication platform for communities and teams',
    url: 'https://discord.com',
    githubUrl: null,
    logo: '🎮',
    tags: 'chat,voice,community,gaming',
    yearCreated: 2015,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'JavaScript,Electron,React',
    alternativeTo: 'Slack,TeamSpeak,Guilded'
  },
  {
    name: 'Matrix',
    type: 'open-source',
    category: 'Communication & Messaging',
    description: 'Open standard for decentralized, secure communication with end-to-end encryption',
    url: 'https://matrix.org',
    githubUrl: 'https://github.com/matrix-org',
    logo: '🔗',
    tags: 'chat,decentralized,encryption,protocol',
    yearCreated: 2014,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Python,TypeScript',
    alternativeTo: 'XMPP,Signal,Telegram'
  },
  {
    name: 'Rocket.Chat',
    type: 'open-source',
    category: 'Communication & Messaging',
    description: 'Open-source team communication platform with omnichannel capabilities',
    url: 'https://rocket.chat',
    githubUrl: 'https://github.com/RocketChat/Rocket.Chat',
    logo: '🚀',
    tags: 'chat,team,messaging,self-hosted',
    yearCreated: 2015,
    selfHostable: true,
    license: 'MIT',
    techStack: 'JavaScript,Meteor,MongoDB',
    alternativeTo: 'Slack,Mattermost,Zulip'
  },
  {
    name: 'Zulip',
    type: 'open-source',
    category: 'Communication & Messaging',
    description: 'Threaded team chat with topic-based organization for productive conversations',
    url: 'https://zulip.com',
    githubUrl: 'https://github.com/zulip/zulip',
    logo: '💭',
    tags: 'chat,team,threaded,productivity',
    yearCreated: 2012,
    selfHostable: true,
    license: 'Apache-2.0',
    techStack: 'Python,Django,PostgreSQL',
    alternativeTo: 'Slack,Discord,Twist'
  },

  // ===== DESIGN & CREATIVE TOOLS (5 projects) =====
  {
    name: 'Figma',
    type: 'saas',
    category: 'Design & Creative Tools',
    description: 'Collaborative interface design tool with real-time collaboration and prototyping',
    url: 'https://www.figma.com',
    githubUrl: null,
    logo: '🎨',
    tags: 'design,ui,prototyping,collaboration',
    yearCreated: 2016,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'C++,WebAssembly,TypeScript',
    alternativeTo: 'Sketch,Adobe XD,Penpot'
  },
  {
    name: 'Penpot',
    type: 'open-source',
    category: 'Design & Creative Tools',
    description: 'Open-source design and prototyping platform with web-based collaborative editing',
    url: 'https://penpot.app',
    githubUrl: 'https://github.com/penpot/penpot',
    logo: '✏️',
    tags: 'design,ui,prototyping,open-source',
    yearCreated: 2020,
    selfHostable: true,
    license: 'MPL-2.0',
    techStack: 'Clojure,ClojureScript',
    alternativeTo: 'Figma,Sketch,Adobe XD'
  },
  {
    name: 'Blender',
    type: 'open-source',
    category: 'Design & Creative Tools',
    description: '3D creation suite supporting modeling, animation, rendering, and video editing',
    url: 'https://www.blender.org',
    githubUrl: 'https://github.com/blender/blender',
    logo: '🎬',
    tags: '3d,modeling,animation,rendering',
    yearCreated: 1994,
    selfHostable: true,
    license: 'GPL-3.0',
    techStack: 'C,C++,Python',
    alternativeTo: 'Maya,3ds Max,Cinema 4D'
  },
  {
    name: 'GIMP',
    type: 'open-source',
    category: 'Design & Creative Tools',
    description: 'Free and open-source image editor for photo retouching and graphic design',
    url: 'https://www.gimp.org',
    githubUrl: 'https://gitlab.gnome.org/GNOME/gimp',
    logo: '🖼️',
    tags: 'image-editing,graphics,photo,design',
    yearCreated: 1996,
    selfHostable: true,
    license: 'GPL-3.0',
    techStack: 'C,Python',
    alternativeTo: 'Photoshop,Affinity Photo,Krita'
  },
  {
    name: 'Canva',
    type: 'saas',
    category: 'Design & Creative Tools',
    description: 'Online graphic design platform with templates for social media, presentations, and more',
    url: 'https://www.canva.com',
    githubUrl: null,
    logo: '🎨',
    tags: 'design,graphics,templates,marketing',
    yearCreated: 2013,
    selfHostable: false,
    license: 'Proprietary',
    techStack: 'JavaScript,React',
    alternativeTo: 'Adobe Express,Crello,VistaCreate'
  }
];

async function main() {
  console.log('🌱 Starting seed...');

  // Clear existing data
  console.log('🗑️  Clearing existing data...');
  await prisma.userRating.deleteMany();
  await prisma.aIRating.deleteMany();
  await prisma.project.deleteMany();

  // Insert projects
  console.log('📦 Inserting projects...');
  for (const project of projects) {
    await prisma.project.create({
      data: project,
    });
  }

  console.log(`✅ Seeded ${projects.length} projects across 10 categories`);
  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
